
### ---------------- Test grupos

GET http://localhost:8888/index.php/grupo HTTP/1.1

###

DELETE http://localhost:8888/index.php/grupo/6 HTTP/1.1


###

POST http://localhost:8888/index.php/grupo HTTP/1.1
Content-Type: application/json

{
    "grupNombre":"Camionetas",
    "grupDescripcion":"Camionetas Toyota modelo 2016"
}


###

PUT http://localhost:8888/index.php/grupo HTTP/1.1

{
    "grupId": 1,
    "grupNombre": "Camionetas",
    "grupDescripcion": "Camionetas Toyota modelo nuevo"
  }



###-------------------- Test Servicio

GET http://localhost:8888/index.php/servicio HTTP/1.1

###

DELETE http://localhost:8888/index.php/servicio/3 HTTP/1.1


###

POST http://localhost:8888/index.php/servicio HTTP/1.1
Content-Type: application/json

{

}


###

PUT http://localhost:8888/index.php/servicio HTTP/1.1

{
 
  }

###-------------------- Test Tarea
GET http://localhost:8888/index.php/tarea HTTP/1.1

###

POST http://localhost:8888/index.php/tarea HTTP/1.1
Content-Type: application/json

{
  "tareNombre": "xxx",
  "tareDescripcion": "xxx",
  "tareUnidadMedida": 22,
  "tareCantidad": 22,
  "tareCosto":1
}

###

PUT http://localhost:8888/index.php/tarea HTTP/1.1

{
  "tareId": 7,
  "tareNombre": "xxx",
  "tareDescripcion": "xxx",
  "tareUnidadMedida": 22,
  "tareCantidad": 22,
  "tareCosto":1
  }