
### ---------------- Test grupos

GET http://localhost:8888/index.php/grupo HTTP/1.1

###

DELETE http://localhost:8888/index.php/grupo/6 HTTP/1.1


###

POST http://localhost:8888/index.php/grupo HTTP/1.1
Content-Type: application/json

{
    "grupNombre":"Camionetas",
    "grupDescripcion":"Camionetas Toyota modelo 2016"
}


###

PUT http://localhost:8888/index.php/grupo HTTP/1.1

{
    "grupId": 1,
    "grupNombre": "Camionetas",
    "grupDescripcion": "Camionetas Toyota modelo nuevo"
  }



###-------------------- Test Servicio

GET http://localhost:8888/index.php/servicio HTTP/1.1

###

DELETE http://localhost:8888/index.php/servicio/3 HTTP/1.1


###

POST http://localhost:8888/index.php/servicio HTTP/1.1
Content-Type: application/json

{

}


###

PUT http://localhost:8888/index.php/servicio HTTP/1.1

{
 
  }

###-------------------- Test Tarea
GET http://localhost:8888/index.php/tarea HTTP/1.1

###

POST http://localhost:8888/index.php/tarea HTTP/1.1
Content-Type: application/json

{
  "tareNombre": "xxx",
  "tareDescripcion": "xxx",
  "tareUnidadMedida": 22,
  "tareCantidad": 22,
  "tareCosto":1
}

###

PUT http://localhost:8888/index.php/tarea HTTP/1.1

{
  "tareId": 7,
  "tareNombre": "xxx",
  "tareDescripcion": "xxx",
  "tareUnidadMedida": 22,
  "tareCantidad": 22,
  "tareCosto":1
  }


###-------------------- Test Servicio Tarea
GET http://localhost:8888/index.php/servicio-tarea HTTP/1.1

###

POST http://localhost:8888/index.php/servicio-tarea HTTP/1.1
Content-Type: application/json

{
    "setaServId":20,
    "setaTareId":6,
}

###

DELETE http://localhost:8888/index.php/servicio-tarea/64  HTTP/1.1
Content-Type: application/json

###-------------------- Test Grupo Servicio
GET http://localhost:8888/index.php/grupo-servicio HTTP/1.1

###

POST http://localhost:8888/index.php/grupo-servicio HTTP/1.1
Content-Type: application/json

{
    "grusGrupId": 1,
    "grusServId": 1,
    "grusPeriodo": 1,
    "grusKM":1,
    "grusFecha": 1 
}

###  -------------------- Test Movil


GET http://localhost:8888/index.php/movil HTTP/1.1

###

POST http://localhost:8888/index.php/movil HTTP/1.1
Content-Type: application/json

{

}

###  -------------------- Test Movil servicio


GET http://localhost:8888/index.php/movil-servicio HTTP/1.1

###
###  -------------------- Test Movil Grupo


GET http://localhost:8888/index.php/movil-grupo HTTP/1.1

###
POST http://localhost:8888/index.php/movil-grupo HTTP/1.1
Content-Type: application/json

  {
    "mogrMoviId": 13389,
    "mogrGrupId": 2
  }

###  -------------------- Test Movil Odometro


GET http://localhost:8888/index.php/movil-odometro HTTP/1.1

###
###  -------------------- Test Movil Bitacora


GET http://localhost:8888/index.php/movil-bitacora HTTP/1.1

###
###  -------------------- Test Movil Mantenimiento


GET http://localhost:8888/index.php/movil-mantenimiento HTTP/1.1

###